import React from 'react';

const Cards = function cards(){
    let card = [
        ["Manager", {
            "Proffesion": 'Менеджер',
            "Income": '4600',
            "Taxes": '910',
            "Mortage_payments_rent" : "700",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '60',
            "Car_load_payment": '60',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '1000',
            "Bank_loan_payment": '0',
            "Children_expanses": '0',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "12000",
            "Car_loans": '6000',
            "Credit_card_debt": '3000',
            "Small_credit": "50",
            "Mortage": "75000",
            "Saving": "400",

        }],
        ["Engineer", {
            "Proffesion": 'Инженер',
            "Income": '4900',
            "Taxes": '1050',
            "Mortage_payments_rent" : "700",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '60',
            "Car_load_payment": '140',
            "Credit_card_payment": '120',
            "Small_credit_payment": "50",
            "Other_expanses": '1090',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "12000",
            "Car_loans": '7000',
            "Credit_card_debt": '4000',
            "Small_credit": "1000",
            "Mortage": "75000",
            "Saving": "400",
        }],
        ["Auto_mechanic", {
            "Proffesion": 'Автомеханик',
            "Income": '2000',
            "Taxes": '360',
            "Mortage_payments_rent" : "300",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '0',
            "Car_load_payment": '50',
            "Credit_card_payment": '50',
            "Small_credit_payment": "50",
            "Other_expanses": '450',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "0",
            "Car_loans": '3000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "31000",
            "Saving": "670",
        }],
        ["Teacher", {
            "Proffesion": 'Учитель',
            "Income": '3300',
            "Taxes": '630',
            "Mortage_payments_rent" : "500",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '60',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '750',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "0",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "50000",
            "Saving": "420",
        }],
        ["Pilot", {
            "Proffesion": 'Пилот авиалинии',
            "Income": '9500',
            "Taxes": '2350',
            "Mortage_payments_rent" : "1300",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '0',
            "Car_load_payment": '300',
            "Credit_card_payment": '600',
            "Small_credit_payment": "50",
            "Other_expanses": '2210',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "0",
            "Car_loans": '15000',
            "Credit_card_debt": '22000',
            "Small_credit": "1000",
            "Mortage": "143000",
            "Saving": "400",
        }],
        ["Secretary", {
            "Proffesion": 'Секретарь',
            "Income": '2500',
            "Taxes": '450',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '0',
            "Car_load_payment": '80',
            "Credit_card_payment": '60',
            "Small_credit_payment": "50",
            "Other_expanses": '570',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "0",
            "Car_loans": '4000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "38000",
            "Saving": "710",
        }],
        ["Nurse", {
            "Proffesion": 'Медсестра',
            "Income": '3100',
            "Taxes": '600',
            "Mortage_payments_rent" : "600",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
        ["Truck_driver", {
            "Proffesion": 'Водитель грузовика',
            "Income": '2500',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
        ["Street_cleaner", {
            "Proffesion": 'Дворник',
            "Income": '1600',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
        ["Advocate", {
            "Proffesion": 'Адвокат',
            "Income": '7500',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
        ["Doctor", {
            "Proffesion": 'Врач',
            "Income": '13200',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
    ]
    return (
        card
    );

};

Cards();

export default Cards;
