import Cards from "./cards"


import React from 'react';

const Events = () => {
    let event = [
        ["Manager", {
            "Proffesion": 'Менеджер',
            "Income": '4600',
            "Taxes": '910',
            "Mortage_payments_rent" : "700",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '60',
            "Car_load_payment": '60',
            "Credit_card_payment": '90',
            "Ыmall_credit_payment": "50",
            "Other_expanses": '1000',
            "Bank_loan_payment": '0',
            "Children_expanses": '0',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "12000",
            "Car_loans": '6000',
            "Credit_card_debt": '3000',
            "Small_credit": "50",
            "Mortage": "75000",
            "Saving": "400",

        }],
        ["Engineer", {
            "Proffesion": 'Инженер',
            "Income": '4900',
            "Taxes": '1050',
            "Mortage_payments_rent" : "700",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '60',
            "Car_load_payment": '140',
            "Credit_card_payment": '120',
            "Small_credit_payment": "50",
            "Other_expanses": '1090',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "12000",
            "Car_loans": '7000',
            "Credit_card_debt": '4000',
            "Small_credit": "1000",
            "Mortage": "75000",
            "Saving": "400",
        }],
        ["Auto_mechanic", {
            "Proffesion": 'Автомеханик',
            "Income": '2000',
            "Taxes": '360',
            "Mortage_payments_rent" : "300",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '0',
            "Car_load_payment": '50',
            "Credit_card_payment": '50',
            "Small_credit_payment": "50",
            "Other_expanses": '450',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "0",
            "Car_loans": '3000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "31000",
            "Saving": "670",
        }],
        ["Teacher", {
            "Proffesion": 'Учитель',
            "Income": '3300',
            "Taxes": '630',
            "Mortage_payments_rent" : "500",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '60',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '750',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "0",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "50000",
            "Saving": "420",
        }],


        ["Street_cleaner", {
            "Proffesion": 'Дворник',
            "Income": '1600',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
        ["Advocate", {
            "Proffesion": 'Адвокат',
            "Income": '7500',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
        ["Doctor", {
            "Proffesion": 'Врач',
            "Income": '13200',
            "Taxes": '400',
            "Mortage_payments_rent" : "400",
            "Home_mortgage_payment": '300',
            "School_loan_payment": '30',
            "Car_load_payment": '100',
            "Credit_card_payment": '90',
            "Small_credit_payment": "50",
            "Other_expanses": '710',
            "Bank_loan_payment": '0',
            "Children_expanses": '250',
            "Per_children_expanses": '240',
            "Home_mortage": '31000',
            "School_loans": "6000",
            "Car_loans": '5000',
            "Credit_card_debt": '2000',
            "Small_credit": "1000",
            "Mortage": "47000",
            "Saving": "480",
        }],
    ]
    return (
        event
    );
};

export default Events;